export interface Client {
  id: number,
  user_id: number,
  created_at:  String,
  updated_at:  String,
  deleted_at:  String,
  name: String,
  fantasyName: String,
  email: String,
  place: String,
  address: String,
  telephone: number,
  cuit: String,
  web: String,
}